### ISSUE TITLE
Vue.js Ktw #1 - Budowa biblioteki komponentów UI w Vue.js na przykładzie Storefront UI.

### ISSUE THREAD

**Issue by pspaczek** [vuejs-poland/katowice#1]
## Tytuł prezentacji
Budowa biblioteki komponentów UI w Vue.js na przykładzie Storefront UI.

## Krótki opis

O tym jak tworzymy open-sourceową bibliotekę komponentów [Storefront UI](https://www.storefrontui.io/) w Vue.js. Jakich narzędzi używamy? W oparciu o jakie konwencje powstają nasze komponenty? Po tej prezentacji będziesz wiedział jak usprawnić tworzenie komponentów w swoim projekcie 🚀. 

## Długość prezentacji
20-30min
## Coś o Tobie
Front-end developer w Divante, Wrocławskim eCommerce Software House. Pracuję nad rozwojem Storefront UI, pierwszej UI-owej libki Vue.js dla eCommerce oraz VueStorefront frontendem PWA dla eCommerce.
## Twoje doświadczenie na meetupach/konferencjach

Vue.js Krk Meetup #2

**Comment by shentao** [comment]
Accepted! @pspaczek
